### ISSUE TITLE
mdns response from python zeroconf returning "empty NSEC block" error

### ISSUE THREAD

**Issue by nc-mcarter** [miekg/dns#1373]
I'm looking to do service discovery using a Golang zeroconf library and am encountering https://github.com/grandcat/zeroconf/issues/34

- The service is exposed by python zeroconf library (https://github.com/jstasiak/python-zeroconf)
- The service is discoverable by avahi-browse
- Debugging grandcat/zeroconf when it attempts to discover the service, it appears that it is getting a "empty NSEC block" error from this library.

Please could you look at the packet below and say if the NSEC record is valid (so issue is in this library), or if this is an issue in what is being sent by the python zeroconf library?

**Wireshark**
[wireshark.zip](https://github.com/miekg/dns/files/8706760/wireshark.zip)

![wireshark](https://user-images.githubusercontent.com/52781930/168770774-b15bb978-a34b-43b3-88f1-c2f432fac0ee.png)

**Service**
Based on https://github.com/jstasiak/python-zeroconf/blob/master/examples/registration.py
```
#!/usr/bin/env python3

""" Example of announcing a service (in this case, a fake HTTP server) """

import argparse
import logging
import socket
from time import sleep

from zeroconf import IPVersion, ServiceInfo, Zeroconf

if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG)

    parser = argparse.ArgumentParser()
    parser.add_argument('--debug', action='store_true')
    version_group = parser.add_mutually_exclusive_group()
    version_group.add_argument('--v6', action='store_true')
    version_group.add_argument('--v6-only', action='store_true')
    args = parser.parse_args()

    if args.debug:
        logging.getLogger('zeroconf').setLevel(logging.DEBUG)
    if args.v6:
        ip_version = IPVersion.All
    elif args.v6_only:
        ip_version = IPVersion.V6Only
    else:
        ip_version = IPVersion.V4Only

    desc = {'path': '/~paulsm/'}

    info = ServiceInfo(
        "_httpexample._tcp.local.",
        "Paul's Test Web Site._httpexample._tcp.local.",
        addresses=[socket.inet_aton("127.0.0.1")],
        port=80,
        properties=desc,
        server="ash-2.local.",
    )

    zeroconf = Zeroconf(ip_version=ip_version)
    print("Registration of a service, press Ctrl-C to exit...")
    zeroconf.register_service(info)
    try:
        while True:
            sleep(0.1)
    except KeyboardInterrupt:
        pass
    finally:
        print("Unregistering...")
        zeroconf.unregister_service(info)
        zeroconf.close()
```

**Client**
Based on https://github.com/grandcat/zeroconf/blob/master/examples/resolv/client.go

```
package main

import (
	"context"
	"flag"
	"github.com/grandcat/zeroconf"
	"log"
	"time"
)

var (
	// _device-info._tcp
	service  = flag.String("service", "_httpexample._tcp", "Set the service category to look for devices.")
	domain   = flag.String("domain", "local", "Set the search domain. For local networks, default is fine.")
	waitTime = flag.Int("wait", 5, "Duration in [s] to run discovery.")
)

func main() {
	flag.Parse()

	// Discover all services on the network (e.g. _workstation._tcp)
	log.Printf("Launching NewResolver looking for service '%s' in domain '%s' for %ds \n", *service, *domain, *waitTime)
	resolver, err := zeroconf.NewResolver(nil)
	if err != nil {
		log.Fatalln("Failed to initialize resolver:", err.Error())
	}

	entries := make(chan *zeroconf.ServiceEntry)
	go func(results <-chan *zeroconf.ServiceEntry) {
		for entry := range results {
			log.Println(entry)
		}
		log.Println("No more entries.")
	}(entries)

	ctx, cancel := context.WithTimeout(context.Background(), time.Second*time.Duration(*waitTime))
	defer cancel()
	err = resolver.Browse(ctx, *service, *domain, entries)
	if err != nil {
		log.Fatalln("Failed to browse:", err.Error())
	}

	<-ctx.Done()
	// Wait some additional time to see debug messages on go routine shutdown.
	time.Sleep(1 * time.Second)
}

```

**Comment by miekg** [comment]
I don't know what 'empty nsec block' means, but the nsec points from ash-2.local to ash-2.local, which is probably not valid.

this library allows you to create nsec's, even these ones, so it's not a problem in this lib.

**Comment by miekg** [comment]
ha, it's our own (bad) error - should fix that

**Comment by nc-mcarter** [comment]
```
So either compression code or nsec packing code is at fault here. First can be tested by disabling compression.
```
Looks like the error still happens with name compression disabled, so I guess that points the finger at the nsec packing code
![wireshark2](https://user-images.githubusercontent.com/52781930/168839737-d5eb6df8-c125-4a72-b1a7-9949622507cd.png)
[wireshark2.zip](https://github.com/miekg/dns/files/8709263/wireshark2.zip)

**Comment by miekg** [comment]
ok, that's good news, thanks for checking. So what generates this record exactly? Not disregarding bugs, but we do operate on garbage in, garbage out. Maybe a nil slice is appended to which could be those first 3 `00` bytes?

**Comment by miekg** [comment]
Ok. So that's python, not this lib. Still looks like an issue somewhere
else.

**Comment by nc-mcarter** [comment]
Yes, I agree that it looks like the issue is coming from elsewhere and not this lib. Will leave the issue open for you to close as and when you're happy with the error detail updates in this lib. Thank you for your help.
